### ISSUE TITLE
Question for Channel attention in KernelGen

### ISSUE THREAD

**Issue by Egkang-Luis** [cszhilu1998/SelfDZSR#10]
Thanks for sharing your great paper and clear code!

I'm beginner for deep learning and super resolution.

I have some question while understanding your code and paper.

If you can explain a little, It will be great to me!

1. Channel attention in KernelGen Class
  - In my understanding, Channel attention should only multiply to Image or feature.
     But In "KernelGen" class, I found add feature as well. Is there any reason or my understanding is not correct?
     "out = head * guide + head"
2. Pre-traning data for "Student_model_400.pth" and "KernelGen_model_400.pth"
  - Provided pre-trained datas("Student_model_400.pth" and "KernelGen_model_400.pth") are great to reproduce your paper result. But I hope to reproduce both data as well("Student_model_400.pth" and "KernelGen_model_400.pth").
    If you don't mind, could you advise how to train both network?

My email address is hyobba1114@gmail.com

Again, I appreciate your great paper and code!

Thanks.

**Comment by cszhilu1998** [comment]
1. Indeed, channel attention generally refers to multiplication operations. "out = head * guide + head" is equivalent to "out = head * (guide +1)". Here the addition operation maybe can be removed. 
2. Please see "3.2 Training" in [README.md](https://github.com/cszhilu1998/SelfDZSR#readme). We also provide training codes.

**Comment by Egkang-Luis** [comment]
For No2 question, I can find provided training code and train the model of selfDZSR.

But I mean that Student_model and Kernel Gen model. 

When I review refsr_model.py, both sub-network must be use pre-trained model repectively.

`
if self.opt.scale == 4:
	self.load_network_path(self.netStudent, './ckpt/nikon_pretrain_models/Student_model_400.pth')
if self.opt.scale == 2:
	self.load_network_path(self.netStudent, './ckpt/camerafusion_pretrain_models/Student_model_400.pth')
if self.isTrain:
	if self.opt.scale == 4:
		self.load_network_path(self.netKernelGen, './ckpt/nikon_pretrain_models/KernelGen_model_400.pth')
	if self.opt.scale == 2:
		self.load_network_path(self.netKernelGen, './ckpt/camerafusion_pretrain_models/KernelGen_model_400.pth')
`

**Comment by cszhilu1998** [comment]
Sorry, I misunderstood. We do not provide separate training codes for KernelGen and Student models. In fact, the training method of the KernelGen model can be seen in the [code](https://github.com/cszhilu1998/SelfDZSR/blob/master/models/refsr_model.py). You can not pre-load it. For the Student model, we follow [C2-Matching](https://github.com/yumingj/C2-Matching). A teacher model is first trained then the Student model is distilled. Related code can refer to [C2-Matching](https://github.com/yumingj/C2-Matching).

**Comment by Egkang-Luis** [comment]
I'll study your code again and C2-Matching!
Thanks for your kind reply!
