### ISSUE TITLE
Question about the chop code

### ISSUE THREAD

**Issue by yyknight** [cszhilu1998/SelfDZSR#2]
Thanks for your impressive code. During checking your code, I notice the chop code is little simple. I'm curious how did you remove the borderline during stiching? Especially, it looks like the image is divided into 36 parts.

**Comment by cszhilu1998** [comment]
First, the divided patches are overlapped. Second, the encoder inputs LR (s_c) and Ref (t_c) in the restoration model (see Fig. B in suppl.) are not divided in the testing phase. This operation provides some global color information of the original image for the divided patches. So our results have little borderline.
