### ISSUE TITLE
Question about the aux LR generator

### ISSUE THREAD

**Issue by yyknight** [cszhilu1998/SelfDZSR#5]
Why did you minus the self.data_hr_bic after generating the aux LR?

**Comment by cszhilu1998** [comment]
'self.data_noise' is generated by downsampling 'self.data_hr' and adding noise to downsampled 'self.data_hr'. 'self.data_noise - self.data_hr_bic' denotes the noise map.

**Comment by yyknight** [comment]
Thanks for your replying! I got it. One more question about the data. From your provided data, it looks like during testing the LR and HR image pairs are still aligned. Then, the output is not the same scene with the original short focus image?

**Comment by cszhilu1998** [comment]
The LR image during testing is still cropped from the original short focus image, as the original short focus image has no corresponding GT. For quantitative evaluation, we have to do it.

**Comment by yyknight** [comment]
Ok, Thanks for your kind reply.
