### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by hzluyali** [cszhilu1998/SelfDZSR#6]
Thank you very much for your release of data pre-process codes. I find that the black space exists in the HR_warp.png. However, there is no black space in the training dataset you released, what is the reason? In addition, because of the use of PWC-Net, I find some regions in HR_warp.png are warped. Will it damage the performance of self-DZSR? By the way, can the short-focus_center.png be directly regarded as the LR? Because of the existence of black regions in the HR_warp.png, I think the there lacks one-to-one correspondence between HR_warp.png and short-focus_center.png.

**Comment by cszhilu1998** [comment]
First, we removed the black space during color alignment (see lines 77-82 in [color_alignment.py](https://github.com/cszhilu1998/SelfDZSR/blob/master/data_preprocess/color_alignment/color_alignment.py)). The short-focus_center.png can not be directly regarded as the LR. It needs to remove the surrounding areas. 
Second, one contribution of SelfDZSR is to mitigate the adverse effects of inaccurate alignment by optical flow, but it may not be perfect.

**Comment by hzluyali** [comment]
Thank you very much for your answer. In addition, I find that the testing dataset consists of cropped shot-focus image and its corresponding 2x telephoto image as HR. During the testing phase, the center part of telephoto image is cropped to guide the super-resolution of the cropped short-focus image. What should I do if I want to directly super-resolve the whole short-focus image with its corresponding 1x telephoto image? In practical case, the size of the short-focus image is the same as the telephoto image, and we want to make full use of the whole telephoto image not the center part of the telephoto image.
