### ISSUE TITLE
Have you utilize the model in multi zoom phones, and how does it works?

### ISSUE THREAD

**Issue by username0occupied** [cszhilu1998/SelfDZSR#7]
I learnt that your aim(background) to develop the algorithm is to super-resolute the mobile phones' images, and I am curious about the effect.

**Comment by cszhilu1998** [comment]
We conducted experiments on images captured by iPhone. The results can be seen in Table 2 and Figure H (in the suppl.).

**Comment by username0occupied** [comment]
Thanks

**Comment by username0occupied** [comment]
Thanks.
