### ISSUE TITLE
Is there any plan to release a code for quick inference?

### ISSUE THREAD

**Issue by hermosayhl** [cszhilu1998/SelfDZSR#8]
As stated above.

**Comment by cszhilu1998** [comment]
Sorry, we don't have this plan at the moment. Calculating the similarity is indeed time-consuming. If you want to speed up the inference, you can refer to [MASA-SR (CVPR 2021)](https://arxiv.org/abs/2106.02299) to improve our code.

**Comment by hermosayhl** [comment]
> Sorry, we don't have this plan at the moment. Calculating the similarity is indeed time-consuming. If you want to speed up the inference, you can refer to [MASA-SR (CVPR 2021)](https://arxiv.org/abs/2106.02299) to improve our code.

Thanks for your code. But I mean, is there any plan to release the code for inference as a quick start.

**Comment by cszhilu1998** [comment]
We still don't have that program recently. You can refer to [test.py](https://github.com/cszhilu1998/SelfDZSR/blob/master/test.py) to customize one.
